### ISSUE TITLE
SGF source integration

### ISSUE THREAD

**Issue by CezCz** [gotoeveryone/gotea#352]
### 対象チケットNo.

SGF source integration

### 概要

Dear Kazuki Kamizuru, 
I am writing a training tool for go, one of it's features is guessing next move in a game.
I am looking for a professional players game collection (for past games) as well as current/future games.
Is there any API (paid or free) that I could use? So in principle the question would be, where are professional sgfs being published?

**Comment by CezCz** [comment]
@gotoeveryone Have you had a chance to see my issue here :) ?

**Comment by gotoeveryone** [comment]
@CezCz 
Sorry, response was later...

First, This is not question section about kifu.
You search about manage site of kifu for such use search engine.

As a side note, I often use site from English.
